### PR TITLE
Some small performance improvements

### PR DESCRIPTION
**Pull request by vsht**
The performance of LinearTest is not optimal when the function is applied
to systems that contain thousands of equations. Using CoefficientArrays
make the function much faster.
 
For example, the attached file lintest.zip contains a system of 6770 linear equations.
On my computer (i5-6440HQ, 32 GB RAM, Fedora 26, Mathematica 11.0) the existing
implementation of LinearTest requires almost 19 seconds, while the suggested version
is done in less than 1 second.

The time required to apply a set of substitution rules (no matter
how simple or short these might be) grows quickly with the size of
the expression to which the rules are applied. This is why one should
try to avoid applying substituion rules (even empty ones like /.{}) to very
large expressions as much as possible. The second patch adjusts the behavior
of SolveSimpleEqns for cases, when no solutions have been found, to that
of ForwardSolve.

When we need to apply a set of substitution rules to a large system of equations,
it is faster to first select those equations, that will actually be affected
by the rule. It appears that in many cases less than 10% of equations are affected,
so that we can significantly reduce the size of the expression that is subject to
the substitution rules. This again improves the performance when the full expression
is much larger than the subset of the affected expressions.

This is not a big thing, but can help to gain a few percent of extra performance.
For example, for the given matrix (c.f. test.zip) CANONICA finishes a few seconds (82 vs 87 seconds
in my case) faster  when this patchset is applied.

[test.zip](https://github.com/christophmeyer/CANONICA/files/1638138/test.zip)
[lintest.zip](https://github.com/christophmeyer/CANONICA/files/1638136/lintest.zip)

### CODE REVIEW

**Comment by vsht** [comment]
UPDATE: The patch fixing Issue #2 is now also included as the 4th commit.

**Comment by christophmeyer** [comment]
Thank you for pointing out these issues. I will have a closer look at your commits next week.

**Comment by vsht** [comment]
Bloß kein Stress und danke für das tolle Package! Bei DGL-Systemen mit mehreren Variablen ist CANONICA aktuell sowieso alternativlos :)

**Comment by vsht** [comment]
Sorry, in the last patch, line 3024
`Message[TransformDiagonalBlock::nonrational];` should be `Message[TransformDiagonalBlock::nonrationaltr];`

**Pull request closed without merging**
